<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>3d4a288f-1796-4a6c-acd4-42754724aafc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#delete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='delete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9d218ef7-8bcd-470e-ac9a-be1b8c9cb703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>delete</value>
      <webElementGuid>e6d2a27e-f996-4c2f-9c97-c347f03ec743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-delete</value>
      <webElementGuid>11d47079-2778-4745-8141-06ef1a1101b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ลบ</value>
      <webElementGuid>52d7fe0a-8578-4989-a499-928e9f37c7a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;card&quot;]/div[@class=&quot;list-all&quot;]/div[@id=&quot;item-control&quot;]/app-todo[1]/div[@id=&quot;i&quot;]/div[@class=&quot;btn-control&quot;]/div[@id=&quot;delete&quot;]</value>
      <webElementGuid>7b965e3f-f9a9-455a-b6bb-8dc7f1e7a67a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='delete']</value>
      <webElementGuid>df96710d-af08-4843-a4f3-c5b1d82bbf95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i']/div/div[2]</value>
      <webElementGuid>0c837951-1a78-4d4c-9927-a0c7e1903da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='เเก้ไข'])[1]/following::div[1]</value>
      <webElementGuid>ee9c25be-4015-4144-b340-5ac70c53b8b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[1]/following::div[6]</value>
      <webElementGuid>0575eecb-ffb8-4333-8394-2c31f13f496b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='เเก้ไข'])[2]/preceding::div[1]</value>
      <webElementGuid>c76147d6-e317-4031-a6c3-9b9cfe4b837a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ลบ'])[2]/preceding::div[2]</value>
      <webElementGuid>93b06d4d-afe1-4400-b342-988b43b5e780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ลบ']/parent::*</value>
      <webElementGuid>9caf5c3f-04b0-4f5d-88cc-0c89c97b21b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-todo/div/div/div[2]</value>
      <webElementGuid>b61a3939-1e39-415e-a33f-2dbabbe077e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'delete' and (text() = 'ลบ' or . = 'ลบ')]</value>
      <webElementGuid>ebb2a066-8804-43f3-bde7-2a775450cd8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
