<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TODO LIST_date-list</name>
   <tag></tag>
   <elementGuidId>dfcc8b41-205b-4c6f-8ea6-38a9bda3660c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#date-list</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='date-list']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c0ac471-59ec-48bb-9835-c07aa3a486c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2f441709-31a2-4922-8bf0-07f4d2e861f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>date-list</value>
      <webElementGuid>339d1d13-a6ad-48fe-a441-92d74b493152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ว/ด/ป</value>
      <webElementGuid>42202e76-b438-4103-b286-33d643a9bd9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>eb8ac939-aa11-432b-aa01-9251ee1aebcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;date-list&quot;)</value>
      <webElementGuid>c5191ce4-01d1-45e7-b600-d862c3dc9833</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='date-list']</value>
      <webElementGuid>698b45ed-a20b-4f40-9d26-0bad0e63ed23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>25b79f46-9c90-47d6-82f0-fbb9c6a82cd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'date-list' and @placeholder = 'ว/ด/ป']</value>
      <webElementGuid>ae32c8f8-57af-4e50-ac44-d0a74814340d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
