<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TODO LIST_name-list</name>
   <tag></tag>
   <elementGuidId>4589a081-e687-44e8-9265-de366cc5be77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#name-list</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='name-list']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e9d459cb-e8fa-4b91-bcc5-1d776088769d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6d7bc538-808b-4cf8-ac1f-e0c37a431529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name-list</value>
      <webElementGuid>1e25ec88-ea8e-4163-b8b1-2b65ba745aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>your goal</value>
      <webElementGuid>0c81c1bb-4b17-45f7-8bfb-86e749b2b962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>83bd732b-1c63-4af0-ad89-b789ad6a61ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>v</value>
      <webElementGuid>eca8622e-d0a8-4087-802a-a9cc14f0a102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name-list&quot;)</value>
      <webElementGuid>8e74bb8b-d273-4f81-b6e9-6f71efb3d307</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='name-list']</value>
      <webElementGuid>3c8052c2-00f3-4db0-92cc-eee88b45f6ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>1bfd2e91-6619-4fdd-91c7-9ab4a7feb041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'name-list' and @placeholder = 'your goal']</value>
      <webElementGuid>1cc5863e-f8aa-4f5a-8351-2f266cf64632</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
